### ISSUE TITLE
nothing is shown after selection

### ISSUE THREAD

**Issue by Carpspb** [Aerilius/sketchup-attribute-inspector#3]
Hi,
I just installe your new version 3.0.0 , but nothing is shown in the AI-Window after selection of groups or components.
![nothing](https://user-images.githubusercontent.com/46330843/58541507-efb67f80-81fb-11e9-9a0b-a43dc6eaa2eb.PNG)

**Comment by Aerilius** [comment]
Thanks for the report!

The screenshot barely shows it, but the select box on the top right seems to be empty, so the dialog is not correctly loaded.

Can you give me two pieces of information:
1. Open _Window → Ruby Console_ and then reopen the Attribute Inspector window. Does it print anything to the console?
2. When you right-click in the Attribute Inspector dialog and choose _Developer Tools_, another window opens. Go to the tab _Console_. Does it display an error message?

**Comment by shkurenkov** [comment]
```
Uncaught promise rejection with reason [ArgumentError]: "wrong number of arguments (given 2, expected 0)"
NoMethodError: undefined method `[]' for nil:NilClassError: #<TypeError: no implicit conversion of String into Integer>
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:498:in `<<'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:498:in `log_error'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:254:in `rescue in __request_handler_htmldialog__'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:213:in `__request_handler_htmldialog__'
Uncaught promise rejection with reason [ArgumentError]: "wrong number of arguments (given 2, expected 0)"
NoMethodError: undefined method `[]' for nil:NilClassError: #<TypeError: no implicit conversion of String into Integer>
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:498:in `<<'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:498:in `log_error'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:254:in `rescue in __request_handler_htmldialog__'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/bridge.rb:213:in `__request_handler_htmldialog__'
Uncaught promise rejection with reason [ArgumentError]: "wrong number of arguments (given 2, expected 0)"
Uncaught promise rejection with reason [NoMethodError]: "undefined method `[]' for nil:NilClass"
Error: #<NoMethodError: undefined method `[]' for nil:NilClass>
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/promise.rb:305:in `unhandled_rejection'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/promise.rb:245:in `reject'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/promise.rb:284:in `call'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/promise.rb:284:in `rescue in block in handle'
C:/Users/alec/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/ae_attribute_inspector/promise.rb:275:in `block in handle'
```

**Comment by nanachi-code** [comment]
experiencing same problem, any update?
