### ISSUE TITLE
error in main.js, nothing is displayed V3.0.4

### ISSUE THREAD

**Issue by tomboul26** [Aerilius/sketchup-attribute-inspector#57]
after selecting a component nothing is displayed, 
So i open the dev-tools; i have this error in devTools

caught ReferenceError: Cannot access 'i' before initialization
    at ./dialogs/components/tree-view-subtree.vue (main.js:2:227061)
    at n (main.js:2:243414)
    at main.js:2:257336
    at main.js:2:286156
    at main.js:2:286160

the source code main.js at line 224061
```
        "./dialogs/components/tree-view-subtree.vue": (e,t,n)=>{
            "use strict";
            n.d(t, {
                A: ()=>i
            });
            const o = {
                components: {
  ->>>>>         TreeViewSubtree: i // <<< here is the error
                },
                beforeCreate() {
                    this.$options.components.TreeViewSubtree = n("./dialogs/components/tree-view-subtree.vue").A
                },
                props: {
                    name: {
                        type: String,
                        default: ""
                    },
                    children: {
                        type: Array,
                        default: ()=>[]
                    },
                    parentPath: {
                        type: Array,
                        default: ()=>[]
                    },
                    nonCommonDictionary: {
                        type: Boolean,
                        default: !1
                    },
                    tree: {
                        type: Object,
                        default: ()=>({})
                    }
                },
                data: ()=>({
                    expanded: !1
                }),
                computed: {
                    id() {
                        return this.path.join("-")
                    },
                    path() {
                        return this.parentPath.slice().concat([this.name])
                    },
                    selected() {
                        return (this.tree.selectedInstance && this.tree.selectedInstance.id) === this.id
                    }
                },
                methods: {
                    handleClickSelect(e) {
                        this.tree._selectInstance(this)
                    },
                    toggleExpand(e) {
                        this.expanded = !this.expanded
                    }
                }
            };
```
and when i select another component i got this error
p.html:1 Uncaught ReferenceError: refresh is not defined
    at app.html:1:1

here some screenshot of dev tools

![2024-07-22_12h19_09](https://github.com/user-attachments/assets/93c43e0a-46d8-47f6-ac1b-f2f69cb7f0ea)
![2024-07-22_12h18_14](https://github.com/user-attachments/assets/cdc1648e-c602-481d-93f8-a21c016aba5b)
![2024-07-22_12h17_24](https://github.com/user-attachments/assets/3a6fe434-8cbd-40cc-a9bb-bce848c021fd)

**Comment by tomboul26** [comment]
so i uninstall 3.0.4 and install 3.0.0 version

but i have this error

![2024-07-22_12h33_28](https://github.com/user-attachments/assets/eadc8939-7d0c-4627-88cd-e910759ba8c3)

and in devtools i have this error, after changing select menu

![2024-07-22_12h33_44](https://github.com/user-attachments/assets/2f8f99b7-5b1f-4b31-bb0c-5fbb12634cd2)

**Comment by tomboul26** [comment]
in the V3.0.4
i take the source code of main.js and change the line 10988
```TreeViewSubtree: i,```
to
```TreeViewSubtree: null,```

and it's seems to work better, but it’s not very stable yet

I dropped version 3.0.0
